
// Loop function
function Call_Loop() {
    //assign Num changing variable
    var Num = "";
    //assign x to 1
    var x = 1;
    //while x remains less than 11 do loop
    while (x < 11) {
        //change num to equal a line break and x
        Num += "<br>" + x;
        //add increment to x
        x++;
    }
    //out put variable num as it increments from the loop.
    document.getElementById("Loop").innerHTML = Num;
}

//set sentence variable
var sentence = "The Panda climbed up the tree.";
//determain variable sentence length
var len = sentence.length;
//write the length of the sentence
document.write(len)

//set animal list as variable
var animals = ["Panda", "Dog", "Cat", "Tiger", "Lion", "Bird", "Gecko"];
var content = "";
var Y;
//loop function to output list
function for_Loop() {
    //if there is no list, and Y length is less than the animal list length (less than 7) increment Y
    for (Y = 0; Y < animals.length; Y++) {
        //content is the list spot the loop is at with a line break
        content += animals[Y] + "<br>";
    }
    //output content list
    document.getElementById("List_of_animals").innerHTML = content;
}

//array function of list index
function array_function() {
    var dog_breeds = [];
    dog_breeds[0] = "Pitbull";
    dog_breeds[1] = "Golden Retriever";
    dog_breeds[2] = "Chihuahua";
    dog_breeds[3] = "shitzu";
    //output concated sentence with index position properties
    document.getElementById("Array").innerHTML = "This dog has the facial features of a " + dog_breeds[0] + ".";
}

//using constant variable in function
function constant_function() {
    //constant variable of Vehicle with properties
    const Vehicle = {brand: "Ford", model: "F150", color: "Red"};
    //change property
    Vehicle.color = "Cyan";
    //add property
    Vehicle.price = "$52000";
    //output 
    document.getElementById("Constant").innerHTML = "The " + Vehicle.brand + " " + Vehicle.model +
    " has a total price of " + Vehicle.price + " and we have one in the color " + Vehicle.color + ".";
}


// var used in this situation is a global variable.
var L = 82;
//writes "82"
document.write("<br>" + L);
{
    //within curly brackets - "let" does not effect outside the curly brackets
    let L = 33;
    //writes "33"
    document.write("<br>" + L);
}
//writes "82"
document.write("<br>" + L);


// var used in this situation is a global variable.
var P = 82;
//writes "82"
document.write("<br>" + P);
{
    //var used in curly brackets -- but not within a function -- is still considered a global variable. It will change with outside code
    var P = 33;
    //writes 33
    document.write("<br>" + P);
}
//writes 33 because of above
document.write("<br>" + P);


//using return within a function
function return_function() {
    //return a random number between 0 and 100
    return Math.random() * 100;
}
//output return of random number generated by function
document.getElementById("Return").innerHTML = return_function()


//let variable with properties using return
let Animal = {
    type : "Panda",
    name : "Fluffy",
    age : "adult",
    color : "Black and White",
    weight: "114 Kg",
    description : function () {
        return "The panda named " + Animal.name + " is a " + Animal.age + " panda that is " + Animal.color + " weighs " + Animal.weight + ".";
    }
};
//output return sentence from description
document.getElementById("Animal").innerHTML = Animal.description();



// constant variable animallist 
const animallist = ["Dog", "Cat", "Horse", "Bird", "Lion", "Hippo"];
let text ="";
//using break in list stops list completely in loop at where break is
list : {
    text += animallist[0] + "<br>";
    text += animallist[1] + "<br>";
    text += animallist[2] + "<br>";
    break list;
    text += animallist[3] + "<br>";
    text += animallist[4] + "<br>";
    text += animallist[5] + "<br>";
}
//outputs only until break as break throws code back out of loop
document.getElementById("animallist").innerHTML = text;



let text2 = "";
//i = 0, if i is less than 10 - increment i
for (let i = 0; i < 10; i++) {
    //when i == 7, skip loop to next number -- continue skips that step and moves to the next.
    if (i == 7) {continue;}
    //text2 is what the variable i is at in that loop with a line break
    text2 += i + "<br>";
}
//output text2 
document.getElementById("continue").innerHTML = text2;
